function com_example_v7_widgetset_V7Widgetset(){var eb='',R=' top: -1000px;',nb='" for "gwt:onLoadErrorFn"',lb='" for "gwt:onPropertyErrorFn"',X='");',ob='#',Rb='.cache.js',qb='/',wb='//',Kb='1ECB5386EC1A074EF566ADE22F0577D2',Lb='2234BD80767DAF6D9A058C6C777E891D',Mb='43A2574517998D1915E6AF75D81C144C',Nb='52C6A073B842EDBC8319DE36FCA71B2E',Ob='86C9C19F2CFFAF7E4BB21C064E39FF27',Qb=':',fb='::',S='<html><head><\/head><body><\/body><\/html>',ib='=',pb='?',kb='Bad handler "',V='Chrome',Pb='DF5E821294C8A9F554583B1746D284A0',U='DOMContentLoaded',M='DUMMY',vb='base',tb='baseUrl',H='begin',N='body',G='bootstrap',sb='clear.cache.gif',K='com.example.v7.widgetset.V7Widgetset',Jb='com.example.v7.widgetset.V7Widgetset.devmode.js',ub='com.example.v7.widgetset.V7Widgetset.nocache.js',db='com.example.v7.widgetset.V7Widgetset::',hb='content',Tb='end',W='eval("',Fb='gecko',Gb='gecko1_8',I='gwt.codesvr.com.example.v7.widgetset.V7Widgetset=',J='gwt.codesvr=',mb='gwt:onLoadErrorFn',jb='gwt:onPropertyErrorFn',gb='gwt:property',ab='head',Eb='ie6',Db='ie8',Cb='ie9',O='iframe',rb='img',Z='javascript',P='javascript:""',Sb='loadExternalRefs',bb='meta',_='moduleRequested',$='moduleStartup',Bb='msie',cb='name',yb='opera',Q='position:absolute; width:0; height:0; border:none; left: -1000px;',Ab='safari',Y='script',Ib='selectingPermutation',L='startup',T='undefined',Hb='unknown',xb='user.agent',zb='webkit';var o=window;var p=document;r(G,H);function q(){var a=o.location.search;return a.indexOf(I)!=-1||a.indexOf(J)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:K,sessionId:o.__gwtStatsSessionId,subSystem:L,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_example_v7_widgetset_V7Widgetset.__sendStats=r;com_example_v7_widgetset_V7Widgetset.__moduleName=K;com_example_v7_widgetset_V7Widgetset.__errFn=null;com_example_v7_widgetset_V7Widgetset.__moduleBase=M;com_example_v7_widgetset_V7Widgetset.__softPermutationId=0;com_example_v7_widgetset_V7Widgetset.__computePropValue=null;com_example_v7_widgetset_V7Widgetset.__getPropMap=null;com_example_v7_widgetset_V7Widgetset.__gwtInstallCode=function(){};com_example_v7_widgetset_V7Widgetset.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[K]={moduleName:K};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(N)[0]}
function y(){if(v){return}var a=p.createElement(O);a.src=P;a.id=K;a.style.cssText=Q+R;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();v.write(S);v.close()}
function z(k){function l(a){function b(){if(typeof p.readyState==T){return typeof p.body!=T&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(U,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(U,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(V)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(W));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(X));g=f.createElement(Y);g.language=Z;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(Y);g.language=Z;g.text=c[i];e.appendChild(g);d(e,g)}}}
com_example_v7_widgetset_V7Widgetset.onScriptDownloaded=function(a){l(function(){m(a)})};r($,_);var n=p.createElement(Y);n.src=k;p.getElementsByTagName(ab)[0].appendChild(n)}
com_example_v7_widgetset_V7Widgetset.__startLoadingFragment=function(a){return C(a)};com_example_v7_widgetset_V7Widgetset.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(Y);c.language=Z;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(bb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(cb),k;if(j){j=j.replace(db,eb);if(j.indexOf(fb)>=0){continue}if(j==gb){k=i.getAttribute(hb);if(k){var l,m=k.indexOf(ib);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=eb}c[j]=l}}else if(j==jb){k=i.getAttribute(hb);if(k){try{d=eval(k)}catch(a){alert(kb+k+lb)}}}else if(j==mb){k=i.getAttribute(hb);if(k){try{e=eval(k)}catch(a){alert(kb+k+nb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;com_example_v7_widgetset_V7Widgetset.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(ob);if(b==-1){b=a.length}var c=a.indexOf(pb);if(c==-1){c=a.length}var d=a.lastIndexOf(qb,Math.min(c,b));return d>=0?a.substring(0,d+1):eb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(rb);b.src=a+sb;a=e(b.src)}return a}
function g(){var a=t(tb);if(a!=null){return a}return eb}
function h(){var a=p.getElementsByTagName(Y);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(ub)!=-1){return e(a[b].src)}}return eb}
function i(){var a=p.getElementsByTagName(vb);if(a.length>0){return a[a.length-1].href}return eb}
function j(){var a=p.location;return a.href==a.protocol+wb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==eb){k=h()}if(k==eb){k=i()}if(k==eb&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return com_example_v7_widgetset_V7Widgetset.__moduleBase+a}
function D(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[xb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(yb)!=-1}())return yb;if(function(){return b.indexOf(zb)!=-1}())return Ab;if(function(){return b.indexOf(Bb)!=-1&&p.documentMode>=9}())return Cb;if(function(){return b.indexOf(Bb)!=-1&&p.documentMode>=8}())return Db;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Eb;if(function(){return b.indexOf(Fb)!=-1}())return Gb;return Hb};i[xb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};s=function(a,b){return b in i[a]};com_example_v7_widgetset_V7Widgetset.__getPropMap=function(){var a={};for(var b in i){a[b]=k(b)}return a};com_example_v7_widgetset_V7Widgetset.__computePropValue=k;o.__gwt_activeModules[K].bindings=com_example_v7_widgetset_V7Widgetset.__getPropMap;r(G,Ib);if(q()){return C(Jb)}var l;try{h([Db],Kb);h([yb],Lb);h([Gb],Mb);h([Eb],Nb);h([Ab],Ob);h([Cb],Pb);l=f[k(xb)];var m=l.indexOf(Qb);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}com_example_v7_widgetset_V7Widgetset.__softPermutationId=g;return C(l+Rb)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Sb,H);r(Sb,Tb)}
A();com_example_v7_widgetset_V7Widgetset.__moduleBase=B();u[K].moduleBase=com_example_v7_widgetset_V7Widgetset.__moduleBase;var F=D();E();r(G,Tb);z(F);return true}
com_example_v7_widgetset_V7Widgetset.succeeded=com_example_v7_widgetset_V7Widgetset();