= Bootstrap

In order to allow the same application code to run in both Vertx and Servlet environments, a bootstrap sequence is used. This is only really needed to enable the Guice Injector to be held in a location suitable to the environment, so that it can be retrieved during link:/userguide/userguide-serialisation.html[deserialisation]

== Bootstrap File

A file called 'krail-bootstrap.yml' should be placed in _src/main/resources_

Even if the application is only required to run in one environment, an entry should be in the file for the other

The *collator* is a fully qualified reference to the `BindingsCollator` implementation which defines the application modules - usually sub-classed from `CoreBindingsCollator`.
Each of the modules is then added to that to form the complete set of modules used in the call to Guice.createInjector()

Make sure you include _uk.q3c.krail.core.guice.ServletEnvironmentModule_ and _uk.q3c.krail.core.guice.VertxEnvironmentModule_

[source,yaml]
----
servlet:
 collator: com.example.myapp.MyBindingsCollator
 modules: 
  - uk.q3c.krail.core.guice.ServletEnvironmentModule
  - com.example.myapp.MyAppModule1
  - com.example.myapp.MyAppModule2
vertx:
 collator: com.example.myapp.MyBindingsCollator
  modules: 
   - uk.q3c.krail.core.guice.VertxEnvironmentModule
   - com.example.myapp.MyAppModule1
 ```
 
This allows a slight variance between the environments with minimum configuration, and has the side effect of reducing the number of classes which need to be defined for each specific application.

If you prefer, you could just have two implementations of ```BindingsCollator``` and leave out the modules from the bootstrap file - but you must ensure that _uk.q3c.krail.core.guice.ServletEnvironmentModule_ and _uk.q3c.krail.core.guice.VertxEnvironmentModule_ are still included

----

servlet:
 collator: com.example.myapp.MyServletBindingsCollator
vertx:
 collator: com.example.myapp.MyVertxBindingsCollator

```